path_to_repositories: "./repositories"
repositories:
    - url: "https://github.com/TheAlgorithms/Python.git"
      name: "Python Algorithms"
    - url: "https://github.com/TheAlgorithms/Java.git"
      name: "Java Algorithms"

file_extensions_to_parse:
    - ".py"
    - ".java"

cleaning:
    .py:
        - "#.*"
        - "\"\"\"[\\s\\S]*?\"\"\""
    .java:
        - "//.*"
        - "/\\*[\\s\\S]*?\\*/"

chunking:
  .py: '^\s*(def\s+.*?:|class\s+.*?:)'

  .java: '^\s*(public|protected|private)?\s*(static\s+)?((class|interface|enum)\s+\w+|[\w<>\[\]]+\s+\w+\s*\(.*?\)\s*\{)'
